### ISSUE TITLE
Infeasible method signature

### ISSUE THREAD

**Issue by nearmax** [near-examples/NFT#117]
As pointed out by external contributor https://stackoverflow.com/questions/65401429/how-to-call-a-near-smart-contract-from-js-with-a-u64-argument NFT implementation uses JSON for its method interfaces, but it also uses u64 which cannot be used with many JSON parsers, including JS. This makes this contract unusable.

**Comment by myklemykle** [comment]
Should the NEAR client js package include a general-purpose BigInt->JSON solution?
https://www.npmjs.com/package/json-bigint (for example)

**Comment by TiGowa** [comment]
I have the same problem when using near-api-js to call Ref-finance contracts:
- contract.get_pool({"pool_id": Int
- contract.get_return({"pool_id": Int 

I receive this error:

{
  "error": "wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: "panicked at \'Failed to deserialize input from JSON.: Error(\"invalid type: null, expected u64\"
}

**Comment by idea404** [comment]
The `BN` or `string` data types are shown in examples for large numbers in JS. 

Will close this issue in the coming days unless somebody still has a reason for performing changes to this repo.
