### ISSUE TITLE
`NEP4::check_access` isn't to spec

### ISSUE THREAD

**Issue by joshuajbouw** [near-examples/NFT#152]
Been looking through the library and had noticed that the NFT example technically isn't to spec on the `check_access` method.

As per spec it states: 
`export function check_access(token_id: TokenId): boolean;`

 which translates to: 
 `fn check_access(&self, token_id: TokenId) -> bool;` 
 in Rust.

However, the NFT example has `fn check_access(&self, account_id: AccountId) -> bool;` as its method.

References:
* [NEP4 Spec](https://github.com/near/NEPs/pull/4)
* [Near NFT example](https://github.com/near-examples/NFT/blob/master/contracts/rust/src/lib.rs#L37)

**Comment by joshuajbouw** [comment]
Closing this for now as I realise that NEP-141 is the standard.

**Comment by djsatok** [comment]
NEP-141 is a standard for fungible tokens. NEP-4 was never accepted. And now there's a new standard for NFTs, though I don't know what is the number for it. @mikedotexe owns this.

**Comment by joshuajbouw** [comment]
NEP-171
