### ISSUE TITLE
NFT did not appear in the wallet

### ISSUE THREAD

**Issue by Valentinishe** [near-examples/NFT#175]
Hey)

If I understand correctly, this is an example of how to design NTF contracts according to the standard. If the contract is designed according to the standard, then the minted tokens should appear in the wallet. Right?

I deployed the contract and followed all the commands from Readme.md, but I cannot see nft in my wallet.

Network: testnet
Contract: market2.plumb.testnet
Account: vkkliq24.testnet

**Comment by onehumanbeing** [comment]
The wallet will consider contracts as non-fungible token contracts relevant to the user if they meet any of the following conditions:

Any account makes a call to the contract with any method prefixed with `nft_` and the `receiver_id` property of the args is the user's account ID.

[Near wallet document](https://github.com/near/near-wallet/blob/1cb459dcdb60e724c1a54b16f524ca80edbbf86b/packages/frontend/docs/NonFungibleTokenDiscovery.md)
