### ISSUE TITLE
nft transfer call GAS

### ISSUE THREAD

**Issue by BenKurrek** [near-examples/NFT#180]
When deploying the token receiver contract and the NFT contract, minting a token and calling `nft_transfer_call` results in an exceeded prepaid GAS error. 

STEPS TO REPRODUCE: 
- build and deploy NFT contract and test-token-receiver
- Call `new` methods on both contracts
- Mint an NFT
- Call `nft_transfer_call` passing in the test-token-receiver contract as the receiver. 

This will result in an exceeded prepaid GAS error as shown [here](https://explorer.testnet.near.org/transactions/38HHDwWvcapsHfNtVnPhSTHnwVoGkfPQ2t1p6wSL939m):

Possible solution / where the problem might stem from: 
In the core standards repo, the GAS attached to the cross contract call is 30 TGas which can be seen [here](https://github.com/near/near-sdk-rs/blob/9b8edfd7f5cb231079b05a1aad9c1203dbab5907/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L376). This might not be enough. 

As an aside - 30 TGas seems like an awful lot of gas and i'm not sure why it would exceed that. In the explorer link [here](https://explorer.testnet.near.org/transactions/38HHDwWvcapsHfNtVnPhSTHnwVoGkfPQ2t1p6wSL939m) where I only call nft_transfer_call, it uses up 26 TGas before failing at the exceeded prepaid GAS which seems strange to me.

**Comment by austinabell** [comment]
related https://github.com/near/near-sdk-rs/issues/559

**Comment by gagdiez** [comment]
please open if still relevant
