### ISSUE TITLE
Error when calling new_default_meta: Unknown argument

### ISSUE THREAD

**Issue by jac2525** [near-examples/NFT#187]
My contract was deployed successfully, but I am having issues with the JSON file. 

When I run this command:

near call $ID new_default_meta '{"owner_id": "'$ID'"}' --accountId $ID

I get this errors:

Unknown argument

or 

SyntaxError: Unexpected token in JSON at position 0 or 1

Any idea? Thanks

**Comment by bucanero** [comment]
If you need support, join our [Discord server](https://near.chat) and check our `#dev-support` channel

**Comment by idea404** [comment]
Closing issue as it pertains to a dev-support matter and Discord support channels have been shared
