### ISSUE TITLE
tests fail on M1 Mac with error[E0425]: cannot find function `get_fault_info` in this scope

### ISSUE THREAD

**Issue by myklemykle** [near-examples/NFT#189]
Hi, 

I'm trying to build the NEP171 example contract (ver 5d9f516) from scratch on MacOS 11.6, M1 CPU.  
Build succeeds, but tests fail here:

```
   Compiling clang-sys v0.29.3
error[E0425]: cannot find function `get_fault_info` in this scope
   --> /Volumes/External/mykle/Documents/near/figment/flarn2.0/registry/src/github.com-1ecc6299db9ec823/wasmer-runtime-core-near-0.17.1/src/fault.rs:289:21
    |
289 |         let fault = get_fault_info(siginfo as _, ucontext);
    |                     ^^^^^^^^^^^^^^ not found in this scope
```

An online search for this error string suggested that this might be an issue with the wasm package requiring rust 'nightly' instead of 'stable'.  But 'nightly' wasn't able to compile or test the build.

**Comment by myklemykle** [comment]
I built successfully on an Intel mac (Mojave 10.14.6) so this is looking like an M1 issue.

In the erroring file wasmer-runtime-core-near-0.17.1/src/fault.rs , get_fault_info() is defined for macos+x86_64, but not for macos+arm.  That's a big clue.

I suspect this is more an issue with building the local NEAR runtime (used for testing?) than the example NFT contract. So probably this issue belongs in a different repo, but I'm not sure which one.  Please advise.  Thx!

**Comment by nhamthanh** [comment]
Yes, I also face this error when run _cargo test -- --nocapture_  on Mac M1
error[E0425]: cannot find function `get_fault_info` in this scope.
Please help us to check this issue.

**Comment by gagdiez** [comment]
should be fixed by now since SDK is compatible with M1 (I am in an M1 now)
