### ISSUE TITLE
When I run "Integration Tests" the mismatched types erro occur

### ISSUE THREAD

**Issue by Fanby1** [near-examples/NFT#211]
I turn the path to `NFT/integration-tests/rs` and run the`cargo run --example integration-tests`.
Then I got 32 erros.
I have already install rust and another Prerequisites but the problem also occur. 
I need some help to fix it.
![截图 2022-10-19 13-28-11](https://user-images.githubusercontent.com/59170837/196605289-4911f7a9-7af9-4e5a-a646-0e30abeb9e82.png)

**Comment by gagdiez** [comment]
should be fixed now, please open the issue if not
