### ISSUE TITLE
check_token function is not there

### ISSUE THREAD

**Issue by servedbyskull** [near-examples/NFT#212]
```check_token``` function is not there. and please also explain if  wanna add my own function where should i put them??

**Comment by mattlockyer** [comment]
It's not part of the standard.

https://nomicon.io/Standards/Tokens/NonFungibleToken/

If you want to add your own functions, you can either add a new file and follow the same use crate convention of the other files or you can add on to the main impl of Contract in lib.rs, it's really up to you.
