### ISSUE TITLE
cleanup punchlist

### ISSUE THREAD

**Issue by amgando** [near-examples/NFT#28]
- [ ] inconsistencies between RS and AS initial steps.  i would prefer that these are symmetrical / 100% parity
https://github.com/near-examples/NFT/blob/master/README.md

- [x] remove simulation unless we're committed to it across both `.wasm` outputs from RS and AS
https://github.com/near-examples/NFT/blob/master/package.json#L13

- [x] missing CI for AS
https://github.com/near-examples/NFT/blob/master/.travis.yml#L13

- [x] start with more tokens?
https://github.com/near-examples/NFT/blob/master/contracts/assemblyscript/nep4-basic/main.ts#L12

**Comment by chadoh** [comment]
> remove simulation unless we're committed to it across both .wasm outputs from RS and AS

I'd be ok with removing from main `package.json` until #10 gets merged; it's quick to add back on that PR

**Comment by chadoh** [comment]
> start with more tokens?

¯\_(ツ)_/¯ 

why not demo a _super scarce & exciting_ NFT? it works for demo purposes and keeps the max-supply test snappy

**Comment by gagdiez** [comment]
deprecated
