### ISSUE TITLE
Make sure NFT is not susceptible to the common vulnerabilities that were found in fungible token example

### ISSUE THREAD

**Issue by nearmax** [near-examples/NFT#40]
There are some common vulnerabilities and inconsistencies that were found in our fungible token example, many of them are not specific to whether the token is fungible or not fungible. We need to make sure NFT does not have them.

Issues to review:
* https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/near/core-contracts/47
* https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/near/core-contracts/54
* https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/near/core-contracts/55
* https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/near/core-contracts/56
* https://app.zenhub.com/workspaces/chainmiddleware-5cea2bcf78297c385cf0ec81/issues/near/core-contracts/57

**Comment by nearmax** [comment]
CC @evgenykuzyakov

**Comment by gagdiez** [comment]
without further information, we have no other option but to close this issue
