### ISSUE TITLE
Running the Rust NFT example contract throws errors

### ISSUE THREAD

**Issue by AnaisUrlichs** [near-examples/NFT#65]
I am on Ubuntu and have Rust already installed. 

Here are the steps I followed:
- Cloning the repository
- Going into the rust folder
- Following the README.md
- running `npm run build:rs` throws the following errors
![Screenshot from 2020-07-14 18-44-21](https://user-images.githubusercontent.com/33576047/87455981-93344080-c606-11ea-8a95-1b923df6d0c7.png)
- I then went to the prerequisites as detailed [here](https://github.com/near/near-sdk-rs) but they are for when Rust is not installed so not helpful in this particular case

@janedegtiareva told me to run the following: `rustup target add wasm32-unknown-unknown` then running `npm run build:rs` worked like expected.

**Comment by mikedotexe** [comment]
Circling back, need to add this link:
https://docs.near.org/docs/tutorials/intro-to-rust#1-install-rustup

**Comment by idea404** [comment]
As solution has been shared, and building contract is now performed without `npm`, I will proceed closing this issue
